### ISSUE TITLE
Teams Mobile App (iOS)

### ISSUE THREAD

**Issue by ChanchalAgrawalMiku** [SAP-samples/btp-bridge-framework#49]
Hi,

Everything is working fine from Teams desktop app. However when clicking the "View More Details" from the Teams Mobile App then it is throwing the below error in BTP backend app logs. Please suggest if we need to add something for Teams Mobile.

```
www-authenticate': 'Basic realm="UAA/client", error="unauthorized", 
error_description="Error validating SAML message"'
...
Error while fetching BTP token Error: Request failed with status code 401
..
getAccessTokenFromSapBtpXsuaa error Error: Request failed with status code 401
..
at createError (/home/vcap/app/node_modules/axios/lib/core/createError.js:16:15)
```

Thanks,
Chanchal

**Comment by AFK-Python** [comment]
Hi Chanchal,

I'm looking into it. We've had bugs with the iOS version before, but hopefully I can get back to you soon.

Best,
Alex

**Comment by AFK-Python** [comment]
Hi @ChanchalAgrawalMiku 

Are you still using principal propagation for the iOS version? Did anything change when you tried the iOS version? The error appears to be coming from a basic authentication error instead of principal propagation or our version of SSO.

Do other parts of the application work on mobile?

Best,
Alex
