### ISSUE TITLE
Question: Deployment Guide

### ISSUE THREAD

**Issue by ghost** [SAP-samples/btp-bridge-framework#9]
- We have four steps to deploy the framework as mentioned in the [https://github.com/SAP-samples/btp-bridge-framework/blob/main/documentation/set-up/Bridge%20Framework%20Deployment.md#bridge-framework-deployment](Link)
- We only see the first step.
- Is there any guide for the remaining steps?

**Comment by I561660** [comment]
> * We have four steps to deploy the framework as mentioned in the [https://github.com/SAP-samples/btp-bridge-framework/blob/main/documentation/set-up/Bridge%20Framework%20Deployment.md#bridge-framework-deployment](Link)
> * We only see the first step.
> * Is there any guide for the remaining steps?

Hi Thien,

I apologize for the inconvenience caused by the incomplete documentation issue. We understand the importance of providing accurate and complete documentation, and we have taken steps to rectify the situation.

Currently with Bridge Framework V2, we provide the option to deploy the bridge framework apps and configure the principal propagation between MS Azure, SAP BTP, and SAP S/4HANA manually, or you can utilize our new automation pipeline docker image to automate the process.

To help you with the deployment, we have prepared detailed instructions that you can follow. Please click on this [link](https://github.wdf.sap.corp/SCE/bridge-framework/blob/master/README.md#getting-started) to access the instructions and complete the deployment process.

Thank you for your understanding and patience.

Best Regards,
Weikun Liu

**Comment by ghost** [comment]
Hi @I561660,

We cannot access your link (https://github.wdf.sap.corp/SCE/bridge-framework/blob/master/README.md#getting-started) as I believe it's intranet site. Can you check the public link.

Thanks,
Thien

**Comment by AFK-Python** [comment]
Hi Thien,

Our apologies, a full guide can now be found [here](https://github.com/SAP-samples/btp-bridge-framework/blob/main/README.md).

If you are trying to set up Bridge manually, then please reference [this guide](https://github.com/SAP-samples/btp-bridge-framework/blob/main/documentation/manual-setup/manual-setup.md).

If you are just trying to deploy Bridge's applications to Cloud Foundry and then register the app to MS Teams, please refer to [this guide](https://github.com/SAP-samples/btp-bridge-framework/blob/main/documentation/manual-setup/app-deployment/manual-deployment.md).

We do recommend using the automated setup tool (mentioned in the full guide), if you can. Please find the docker image to set it up under our release page. Note, we are currently experiencing some problems with the apple chip/M1 version of the container - we hope to release an updated docker image there soon.

If you have any further questions, please let us know!

Best,
Alex

**Comment by ghost** [comment]
Hi @AFK-Python (Alex)

Thanks a lot. We will try and revert if there is any challenges. For now, I will close the issue.

BR,
Thien
